---
title: "CyTOF Raw Event Type Summary Report"
author: "Generated by cytofQC"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
    runUMAP: TRUE
---

```{r setup, include=FALSE}
library(uwot)
library(RColorBrewer)
knitr::opts_chunk$set(echo = FALSE)
```

```{r load_data}
res <- readRDS('cytofQCdata.rds')
tech <- res$tech
labels <- res$labels
rm(res)
stopifnot(nrow(tech) == nrow(labels))
message('Found ', nrow(tech), ' events.', '\n')
message('Found the following technical variables:','\n',
        paste(colnames(tech), collapse = ', '), '\n')
```


## Event type summary

```{r table1}
cbind(count = table(labels$label), 
      percent = round(100 * table(labels$label) / nrow(labels), digits = 2))
```

## Technical UMAP

```{r umap}
if(params$runUMAP){
    s.tech <- scale(tech[, -1])
    umap <- uwot::umap(s.tech)
    
    require(RColorBrewer)
    cols <- brewer.pal(5, "Set2")
    layout(matrix(c(1,1,2), nrow=1))
    plot(umap, asp=1, col = cols[labels$label], cex = .25, pch=16,
         main = "UMAP on Technical Variables")
    plot.new()
    legend("left", pch=19, col = cols, legend = levels(labels$label), bty='n')
}
```

