#' Generate a cytofQC report
#'
#' @param tech A matrix of technical variables, as generated by
#'   \code{\link{dataPrep}}
#' @param labels A \code{data.frame} containing predicted event labels, as
#'   generated by \code{\link{labelQC}}
#' @param outDir The output directory (currently required).
#' @param sampName Basename of the output HTML file (if not provided, same as
#'   \code{outDir}).
#'
#' @return If successful, returns \code{TRUE} silently and generates the
#'   specified QC report.
#'
#' @examples
#' fname <- system.file("extdata", "raw_cytof.fcs", package = "cytofQC")
#' tech <- dataPrep(fname)
#' labels <- labelQC(tech, types = c("bead", "doublet", "debris"), nTrain = 1000)
#' tmp <- tempdir()
#' generateReport(tech, labels, tmp, 'example')
#' 
#' @importFrom rmarkdown render
#' @export
generateReport <- function(tech, labels, outDir, sampName, ...){
    stopifnot(dir.exists(outDir))
    if(missing(sampName)){
        sampName <- basename(outDir)
    }
    if(missing(labels)){
        labels <- labelQC(tech, ...)
    }
    labels$label <- factor(labels$label, levels = c("cell", "GDPzero", "bead", "doublet", "debris"))
    out <- list(tech = tech, labels = labels)
    
    # temporarily store results on disk
    saveRDS(out, file = file.path(outDir, 'cytofQCdata.rds'))

    template <- system.file("extdata", "template.Rmd", 
                            package = "cytofQC", mustWork = TRUE)

    ## Copy the template file to outDir
    file2Knit <- file.path(outDir, paste0(sampName,'.Rmd'))
    cp <- file.copy(template, file2Knit, overwrite = TRUE)
    if(!cp){
        msg <- paste("Template file was not able to be copied.",
            "Do you need to set overwrite = TRUE",
            "or check write permissions?")
        stop(msg)
    }
    stopifnot(file.exists(file2Knit))
    
    ## Compile the document in the directory
    rmarkdown::render(
        file2Knit,
        output_dir = outDir,
        envir = new.env()
    )
    message("done")
    
    # remove data and template
    file.remove(file.path(outDir, 'cytofQCdata.rds'))
    file.remove(file2Knit)
    
    return(invisible(TRUE))
}
